### ISSUE TITLE
Should we build libxeus.a with -fPIC (CMAKE_POSITION_INDEPENDENT_CODE=ON)

### ISSUE THREAD

**Issue by SylvainCorlay** [conda-forge/xeus-feedstock#60]
That would enable third-parties to produce shared objects linking with `libxeus.a`.

Although it would bloat a bit the binary size...

**Comment by JohanMabille** [comment]
The policy is to use either static libraries of shared libraries, but avoid mixing them. Therefore, no need to build libxeus.a with -fPIC flag.
